### PR TITLE
Germanic runes tutorial

### PR DESCRIPTION
**Pull request by clemsciences**
Everything is in the notebook

### CODE REVIEW

**Comment by clemsciences** [comment]
Is not it ok?

**Comment by kylepjohnson** [comment]
Thanks for the reminder.

**Comment by clemsciences** [comment]
Thank you for the merge! I absolutely don't know if these tutorials in Old Norse are useful to anyone? At least it can give ideas to some contributors.

In a next pull request, I will use the new runic corpus, available here https://github.com/cltk/old_norse_runes_corpus, in this tutorial.

**Comment by kylepjohnson** [comment]
I can't say how many are using them now, however what you are doing is exactly what we need, in order to help new users understand how to use the cltk.

Have you promoted these among your colleagues in Europe?

**Comment by kylepjohnson** [comment]
> In a next pull request, I will use the new runic corpus, available here https://github.com/cltk/old_norse_runes_corpus, in this tutorial.

Latest version 0.1.91 has it and is on pypi: https://github.com/cltk/cltk/blob/d123c94f6319ca70a931cdbb6305b408345bff64/cltk/corpus/old_norse/corpora.py

**Comment by clemsciences** [comment]
I can't say how many are using them now, however what you are doing is exactly what we need, in order to help new users understand how to use the cltk.

It's good to read it! 

    Have you promoted these among your colleagues in Europe?

The problem is that I don't have colleagues in NLP domain. And I'm not a PhD student anymore (I stopped for health reasons, but no worry, I'm fine now) and my the topic of my doctorate was image sequences classification. My official background in NLP was working on POS taggers during the last year project as a student and a 6 month internship in UKP in Darmstadt in multi-document summarization. So I contribute to CLTK during my free time. The only way I have to promote this is Twitter.

    Latest version 0.1.91 has it and is on pypi: https://github.com/cltk/cltk/blob/d123c94f6319ca70a931cdbb6305b408345bff64/cltk/corpus/old_norse/corpora.py
Yes thank you! I realized it too late. I'm doing the necessary modifications in my this notebook.

**Pull request merged**
