### PR TITLE
Proofread tutorials

### PR DESCRIPTION
**Pull request by aurelberra**
As I refreshed my knowledge of how the CLTK works, I went through all notebooks and proofread them. Hope this helps!

### CODE REVIEW

**Comment by aurelberra** [comment]
I also went on to add Greek examples after the Latin ones. I have a [branch with those proofread and extended files](https://github.com/aurelberra/tutorials/tree/tutorials_greek/tutorials_latin_and_greek). Before making a pull request for these slightly deeper changes, I'd like to know if you're interested in merging them into the initial tutorials.

Thanks for all your work on the CLTK!

**Review by kylepjohnson — APPROVED** [review]
Thank you and sorry it took 2 weeks to get to this.

**Comment by kylepjohnson** [comment]
> I also went on to add Greek examples after the Latin ones. I h

Yes, Greek examples would be excellent! Please do send a PR

**Comment by aurelberra** [comment]
Thanks! I have sent the PR.

**Pull request merged**
