### PR TITLE
Tutorial 9 notebook updated

### LINKED ISSUE #17: Possible edit in Tutorial 9 notebook - importing of indian_punctuation_tokenize_regex
In the [Tutorial 9](https://github.com/cltk/tutorials/blob/master/9%20Lexical%20Dispersion%20Plot.ipynb), importing of `indian_tokenizer `might fail. This is probably because `indian_tokenizer` is now a part of `sentence.py` as a result of [702](https://github.com/cltk/cltk/pull/702) and `indian_punctuation_tokenize_regex()` is now a part of class `TokenizeSentence()` 
Although there is no example of this function being used in this Tutorial notebook, the error due to import can be avoided.

### PR DESCRIPTION
**Pull request by siddharthkv7**
Fixes #17 .
@kylepjohnson  When I ran the notebook, I encountered an error. Hence, I tried to do the same task by instantiating the class  `TokenizeSentence()` instead instead of calling 'indian_punctuation_tokenize_regex()'.
Please review the changes. Feedback would be very much appreciated.
PS: I also think we could add examples from one of the Indian languages in the notebook to show its working. Please let me know if I can do so, I shall edit the notebook again :)

### CODE REVIEW

**Review by kylepjohnson — APPROVED** [review]
Looking good thank you

**Comment by kylepjohnson** [comment]
Now that you have the hang of Jupyter, go ahead and try to make a few notebooks specific for Indian languages. You can follow the pattern set by @aurelberra in https://github.com/cltk/tutorials/tree/master/languages/old-norse

**Comment by siddharthkv7** [comment]
@kylepjohnson Thank you. I will get right on to it. :)

**Comment by clemsciences** [comment]
@kylepjohnson, I made the Old Norse notebooks :p

**Comment by siddharthkv7** [comment]
I know! Thanks @clemsciences anyway, your notebook helps my cause :)

**Comment by kylepjohnson** [comment]
D'oh! Sorry @clemsciences I knew that.

**Pull request merged**
