### PR TITLE
Add Greek examples

### PR DESCRIPTION
**Pull request by aurelberra**
I added Greek examples after the Latin ones.

### CODE REVIEW

**Comment by kylepjohnson** [comment]
Thx for this. I have to merge the conflicts myself, on my own computer. I'll try to do this sometime in the next week.

**Comment by aurelberra** [comment]
Great! Let me know if I can do something.

**Comment by aurelberra** [comment]
Hi. I am about to send a link to the tutorials to a colleague who asked me about the CLTK. He works on Greek literature and science. If you could merge the Greek examples now, that would be a perfect timing – and it would be good for CLTK evangelism!

**Comment by aurelberra** [comment]
Pointing to the updated tutorials would still be very useful, this time for students using the CLTK.

**Comment by kylepjohnson** [comment]
Aurélien, I am really sorry I did not merge this earlier :sweat_smile: 

I merged your updates by command line. I also have given you write access to this repo, so please go ahead and make fixes as you see fit.

**Comment by kylepjohnson** [comment]
FYI here is my merge of your code: https://github.com/cltk/tutorials/commit/6bd4157b294e3cce8e6587b701fe3de7cba037de

And tutorials links added to the README ( https://github.com/cltk/cltk#tutorials ) and an entire doc page for it, too: http://docs.cltk.org/en/latest/tutorials.html

Again, I apologize for being so slow to merge this. If there is something special you want to do with these tutorials (or anything else), let me and @diyclassics know, and we can support you doing it directly, without waiting on us.

**Comment by aurelberra** [comment]
Thanks! It's good to see these tutorials in the docs.

I certainly learn a lot from and with the CLTK, and hope to be able to further contribute somehow.

**Comment by kylepjohnson** [comment]
Great! I made first made these to help teach NLP during a lecture. If you teach, then giving these to students is the best way to break -- and improve -- them!

**Pull request closed without merging**
